// <auto-generated />
using System;
using MemoryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoryApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203225004_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("MemoryApp.Data.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiFeedbackEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiSystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AiTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Attempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreDelta")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathOrData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Noun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("German")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plural")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationEs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("German")
                        .IsUnique();

                    b.ToTable("Nouns");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Sentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentenceTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationEs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.UserNounProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NounId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "NounId");

                    b.HasIndex("NounId");

                    b.ToTable("UserNounProgress");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyGoal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UiTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.UserVerbProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "VerbId");

                    b.HasIndex("VerbId");

                    b.ToTable("UserVerbProgress");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auxiliary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIrregular")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeparable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartizipII")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PraeteritumIch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationEs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Infinitive")
                        .IsUnique();

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.VerbForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VerbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VerbId");

                    b.ToTable("VerbForms");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.VerbImage", b =>
                {
                    b.Property<int>("VerbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VerbId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("VerbImages");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Attempt", b =>
                {
                    b.HasOne("MemoryApp.Data.Models.User", "User")
                        .WithMany("Attempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Sentence", b =>
                {
                    b.HasOne("MemoryApp.Data.Models.Verb", "Verb")
                        .WithMany("Sentences")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.UserNounProgress", b =>
                {
                    b.HasOne("MemoryApp.Data.Models.Noun", "Noun")
                        .WithMany("UserProgress")
                        .HasForeignKey("NounId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryApp.Data.Models.User", "User")
                        .WithMany("NounProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noun");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.UserSettings", b =>
                {
                    b.HasOne("MemoryApp.Data.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("MemoryApp.Data.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.UserVerbProgress", b =>
                {
                    b.HasOne("MemoryApp.Data.Models.User", "User")
                        .WithMany("VerbProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryApp.Data.Models.Verb", "Verb")
                        .WithMany("UserProgress")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.VerbForm", b =>
                {
                    b.HasOne("MemoryApp.Data.Models.Verb", "Verb")
                        .WithMany("Forms")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.VerbImage", b =>
                {
                    b.HasOne("MemoryApp.Data.Models.Image", "Image")
                        .WithMany("VerbImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryApp.Data.Models.Verb", "Verb")
                        .WithMany("VerbImages")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Image", b =>
                {
                    b.Navigation("VerbImages");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Noun", b =>
                {
                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.User", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("NounProgress");

                    b.Navigation("Settings");

                    b.Navigation("VerbProgress");
                });

            modelBuilder.Entity("MemoryApp.Data.Models.Verb", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Sentences");

                    b.Navigation("UserProgress");

                    b.Navigation("VerbImages");
                });
#pragma warning restore 612, 618
        }
    }
}
